### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by MikeBergmann** [anikinmd/zed_bitbake#2]
I'm having unusual syntax highlighting using zed 0.151.1 on Ubuntu  and bitbake extension 0.0.2

![Screenshot from 2024-09-05 13-32-33](https://github.com/user-attachments/assets/88675679-f7ae-4d70-aab0-2b1f3000b23f)

**Comment by anikinmd** [comment]
@MikeBergmann, I see
Somehow, line 149 breaks the syntax highlight

**Comment by anikinmd** [comment]
What happens is that bitbake and bash syntax overlap each other. I need to add a bash tree-sitter and figure out how to make it work only for bitbake functions. 
Any suggestions are appreciated.

**Comment by jdelbefoss** [comment]
What about trying to detect the do_* functions as bitbake tasks?
Maybe at least the well-known ones?
https://docs.yoctoproject.org/dev/ref-manual/tasks.html

**Comment by anikinmd** [comment]
That's what I thought to do. Also, We may need a tree-sitter for Python, as bitbake recipes can have Python functions and anonymous Python functions.
The problem is that config.toml allows configuring tree-sitter usage by file name/extension pattern (.bb, .bbappend). I don't see the possibility of configuring it by some text pattern inside the file.

UPD: this looks promising:
https://github.com/zed-industries/zed/blob/main/docs/src/extensions/languages.md#code-injections

**Comment by anikinmd** [comment]
@MikeBergmann Fix was merged into the extensions repo.

**Comment by anikinmd** [comment]
@MikeBergmann Did you try an update?

**Comment by MikeBergmann** [comment]
@anikinmd Yes, thanks a lot. It's looking much better now.
